screen:
    # specifying the top-left corner of the game window
    screen_left: 1759
    screen_top: 1097
    # the part of the window which shows the world
    play_screen_width: 520
    play_screen_height: 340

inventory:
    inventory_left: 550
    inventory_top: 209
    inventory_width: 167
    inventory_height: 252

tooltip:
    # these are relative to the top-left corner of the game window
    tooltip_left: 4
    tooltip_top: 5
    tooltip_width: 250
    tooltip_height: 25

classifier:
    classifier_dir: classifiers/chickens/classifier/cascade.xml